module.exports.authService = require('./auth.service');
module.exports.emailService = require('./email.service');
module.exports.tokenService = require('./token.service');
module.exports.userService = require('./user.service');
module.exports.subscriptionService=require('./subscription.service')
module.exports.purchaseService=require('./purchase.service')
module.exports.workoutGameService=require('./workoutGame.service')
module.exports.arrowGameService=require('./arrowGame.service')
module.exports.pictureMatchService=require('./pictureMatch.service')