module.exports.authController = require('./auth.controller');
module.exports.userController = require('./user.controller');
module.exports.subscribtionController=require('./subscription.controller')
module.exports.purchaseController=require('./purchase.controller')
module.exports.workoutGameStatusController=require('./workoutGame.controller')
module.exports.speedTappingController=require('./speedTapping.controller')
module.exports.arrowGameController=require('./arrowGame.controller')
module.exports.pictureMatheController=require('./picterMatch.controller')
module.exports.mathquizegameController=require('./mathquiz.controller')
module.exports.subscriberController=require('./subscriber.controller')